### PR TITLE
Move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by kjsanger**

### CODE REVIEW

**Comment by kjsanger** [comment]
Despite what github says, this branch is only one commit ahead of wtsi-npg/devel

**Comment by dkj** [comment]
Looks fine but 
- do we want/need to use Perlbrew? We're using native Ubuntu packaged Perl everywhere apart from seq-farm2 now _I think_.
- how does the caching compare with `npg_seq_pipeline` - that's more complex perhaps than this (no NPG dependencies) requires

**Review by dkj — APPROVED** [review]
Would rather have merged than not, but:
- not sure we need PerlBrew at the moment
  - I don't think it does harm
  - could be useful for perl version permutations
  - doesn't cover our use of OS Perl
- the git commit history GitHub gives does surprise me (so glad of reassurance given)

**Comment by kjsanger** [comment]
> Would rather have merged than not, but:
> 
>     * not sure we need PerlBrew at the moment
>       
>       * I don't think it does harm
>       * could be useful for perl version permutations

I used PerlBrew because 

- allows us to retain the tests that we already use on both 5.16 (legacy genotyping code is running on 5.16) and
5.22 (everything on the seq farm) whereas bionic perl is 5.28.1

- using official the Perl containers (for speed of deployment) caused the tests to run in the container, which broke caching.

>       * doesn't cover our use of OS Perl

OS === operating system or OS == OpenStack? Assuming the former, although I think they coincide.
Using the Actions runner's Perl doesn't cover it either; Perl on the seq fleet is 5.26.1, while on bionic
it's 5.28.1, plus it's subject to change when the runner is updated.

 In what way should we expect an OS install of e.g. perl 5.28.3 to behave differently from a Perlbrew 5.28.3, particularly in the scope of these tests, which are units? I would expect no difference at all.

Downsides of Perlbrew:

1. Limited set of patch versions of Perl e.g. 5.28.3, but not 5.28.1
2. Occasional long running builds when the cache is broken.

I'm not advocating Perlbrew - it's a workaround for getting testing back up in the very limited time
available.

>     * the git commit history GitHub gives does surprise me (so glad of reassurance given)

**Comment by dkj** [comment]
> * allows us to retain the tests that we already use on both 5.16 (legacy genotyping code is running on 5.16) and
>   5.22 (everything on the seq farm) 

:+1:

> * using official the Perl containers (for speed of deployment) caused the tests to run in the container, which broke caching. I tried to fix that by mounting the cpanm directories on a Docker volume, but it didn't have the desired effect and I didn't want to get side-tracked on debugging that remotely.

Good to know.

> Using the Actions runner's Perl doesn't cover it either; Perl on the seq fleet is 5.26.1, while on bionic
> it's 5.28.1, plus it's subject to change when the runner is updated.

My mistaken assumption here - thanks.

**Pull request merged**
